apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-pod-app
  labels:
    name: result-pod-app
    app: demo-voting-app
spec:
  template:
    metadata:
      name: result-pod-app
      labels:
        name: result-pod-app
        app: demo-voting-app

    spec:
      containers:
        - name: result-pod-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      name: result-pod-app
      app: demo-voting-app