apiVersion: v1
kind: Pod
metadata:
  name: result-pod-app
  labels:
    name: result-pod-app
    app: demo-voting-app

spec:
  containers:
    - name: result-pod-container
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80