apiVersion: v1
kind: Pod
metadata:
  name: voting-pod-app
  labels:
    name: voting-pod-app
    app: demo-voting-app

spec:
  containers:
    - name: voting-pod-container
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80